version: "3.7"
services:
  postgresql:
    container_name: temporal-postgresql
    image: postgres:13
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"
    networks:
      - temporal-network

  temporal:
    container_name: temporal
    image: temporalio/auto-setup:1.22.3
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    volumes:
      - ./config/dynamicconfig:/etc/temporal/config/dynamicconfig
    ports:
      - "7233:7233"
    depends_on:
      - postgresql
    networks:
      - temporal-network

  temporal-admin-tools:
    container_name: temporal-admin-tools
    image: temporalio/admin-tools:1.22.3
    networks:
      - temporal-network
    depends_on:
      - temporal

  temporal-web:
    container_name: temporal-web
    image: temporalio/web:1.15.0
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    ports:
      - "8088:8088"
    networks:
      - temporal-network
    depends_on:
      - temporal

networks:
  temporal-network:
    driver: bridge